spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:weplan
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create # 개발환경에서는 편의상 create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug

# 운영환경과 다른 개발용 jwt 키 값
jwt:
  key: OewPcNeX7cy++FrTqVsB14Fg8kC9xaphxD9LEdWu170=
